version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: employee-management-postgres
    ports:
      - "5433:5432"
    expose:
      - "5432"
    restart: always
    environment:
      TZ: "America/Sao_Paulo"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: employee_management